travis:
  secure:
    BINSTAR_TOKEN: D2caRLGHRVlUM4Xeh74vUpRcg0WEWMMZ7IXDxAuFFY5oK38XSCDgCvCGJDBlBkIggANZUurC7DPxDvj218Kq1TQr4Vtn4oF08Re+o6ZSp8wxHifTbLBipXLrGYVT5tNW9m0APzC3MkDAM9SIv/Cx9SzpgW9tyIleTWVnWu/yA5QmRgm/tYJKRU1zVVeHmKTVQN+2eeFC16BaEyZWQ+aEYyAH2TJt96mu1znmUQR6lr7s0tvRmaocnewOmCAAjTlmihBpN94s7n5g0gdnaWI0Y+rnY77WqmwsQcUatJCIGZZFfaVmIferdbkb6bNZIxCHaH5inTE0oo7oIBYALN5BwFoM5S8LdQrWv2fR6y7cjqSFcWuQHGo5FaZDb4ikkHOiqtcCFHM6nyqEo56nzd8FPJIe4YB3FoGBBD/Wnpb3zf91HmnJNClzb3G/09jhBQUpciZ4BGNCN4QtgwWAOiZQFtqWipj8E994Qk9UW96lhfejmTnt2hFVpsdzOTY9N+DzArQF8BzNAlNZfYUvXz/fscp/uArPapXrj0SH9/i3o2z5mmep4slZ+0H7JCWxwTknP/zWoI1BhBwNNp810ymnyeEnndFBnamWqYuklbaViyvnaxOIAnZ7Jdm/ZeATqGNrnSUZGP+Ek7ImleWfEQT5ZJbVErIPP2TnGNk3RbtXkFI=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
