travis:
  secure:
    BINSTAR_TOKEN: xkemshtW0O3PgELz63cEv1EhuqQSmgUT3vBk3fJD7qcqHPnxodYqDbQvulIufk41kQ7+aUSFK1hGg8MEplQKkTxYWIda5Drf1tvvx7MIQ7h7Dm1aFC+mgNdg/lxPnKlYh0TZacYnhcNVQ/nldBUFaFyEVpQuV7TDursz5AZFGERXt9U2LX6htbywHWF1nWQEqprCKLCE9oYcCRzbynJtNll9FChhF9YadoYiBSG3M4kGJ5Jokx3GIXRrgCfQTfe8wFBwd3CMPNnrfeiDud3ZOhxIBNFABiuaOXDZQ6w46wLpVE2/CcHBkes5pb6ZqlFDZWRrmDKICqxmA6bAPDqReWklJbHM3QVmGQ00OFUXMRUBfrKDHmKd11iOsKR1cXh/g+hzfCtWEqccbtiuv3hX/4yj5cYV10JFHAMzwav1/Jd17a0+UWb50Dl+OgWP+qsBEnlSGJ1fULO9HZno9jaBeRcrmMjiQHuNF6nCz5T+Gvy2j/N1CiI/LpNkHedolQkv0/MDxePnnJkGssLlv2XpRMQdaPOq8Pem4hGigna4Ztx2K4ZyhdNQyLj+8oPFq7kf0EAZkkZfquGUthxa5Bwt6zJYpZVh+NxdTRLrSgcADEizJFyis1ObGQunuwEews1WBoYysb5AQB9z1aKVvmLEJ45AI5TgFaQyRPOzf4CtgpI=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
